name: Health Check

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */12 * * *'

jobs:
  health_check:
    runs-on: ubuntu-latest
    
    steps:

      - name: Pull the latest Docker Image
        run: |
          docker pull ${{ secrets.DOKERHUB_USER }}/capstone-app:latest

      - name: Run container
        run: |
          docker run -d -p 8080:8080 --name health-check-container ${{ secrets.DOKERHUB_USER }}/capstone-app:latest

      - name: Wait for container to start
        run: sleep 5

      - name: Check Health Endpoint
        id: health
        run: |
          STATUS=$(curl -s -o /dev/null -w  "%{http-code}" http://localhost:8080)

          if [ $STATUS -eq 200 ]; then
            echo "Health check is PASSED"
            echo "status=PASSED" >> $GITHUB_OUTPUT
          else
            echo "Health check is failed"
            echo "status=FAILED" >> $GITHUB_OUTPUT
            exit 1
          fi

      - name: Stop and Remove container
        if: always()
        run: |
          docker stop health-check-container && docker rm health-check-container

      - name: Generate Health check Summary
        run: |
          echo "## Health Check Report" >> $GITHUB_STEP_SUMMARY
          echo "- Image: myapp:latest" >> $GITHUB_STEP_SUMMARY
          echo "- Status: PASSED" >> $GITHUB_STEP_SUMMARY     
          `echo "- Time: $(date)" >> $GITHUB_STEP_SUMMARY
